import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from '../providers';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-zinc-900 text-white`}>
        <AnnouncementBar />
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}

function AnnouncementBar() {
  return (
    <div className="bg-gradient-to-r from-blue-600 to-blue-800 text-white text-sm py-2 text-center">
      Fixing auth related issues. Don't signup yet!
    </div>
  );
}
